language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: cJj6S1ZxSc18p0ioaIuGeht6EBeDMsNZmLhyDglg07ahieskST0CcJZ0q6XfR1os3XYkvVhEhY/V/l1oYXLdSaPrq0IPuPgXW/A5UVKcz0sDzfMIRFdGDN5QjvSmuWjjPK/p1JWc4/UAB3jtXBeQqpSAgL0swdiDJ31Yv9wPpPA/JSw/j/pwWFgo9RZdGSfngNg6NmNehs7XvHPTSHwYoPfzjBdrWUNL2BmD6yOZt1kUR+8aAQah0a290acPYhjiuOmLu0Eg8s65mFRJ4S7jqW6fS8W83K1B86UloneCGIsE6Sq4YiM0OpVcuGFhZrpGgmsYTXRPLCZjmWm/1onyWy8HCDYsR+3xhtsVu3Ot8qi9mUH7WrZ5TIvQN1H+awjPLxaMK8IiYrrIqTBAMjJ5JwfovRGu8yEpzVwUbjhrnlXkRErmzsuKrd6tzhJe648BYkD9/+DZLiaTWuWTrbLslQ9Yj9TILOf0+1mBAbrL0eBaIj4CbuLr0cjmWS9G3LImu1rLZOJLRWeDU0EjAANOF2YPzapatQFl4hGc1E4jE5aia1UvcdQC5NqQx7hVE23MKmfe/xiLcYvg7jEIvw7fYDYsySwcyQU1JCQYnt4By/iPJTqEEUU/6xjeTWKBL5Le5G7oaC2fHmf+U/3WHF2Qf+xjp2Z1/Yq9kXdAbDdIafU=
  app: waxstack
  on:
    repo: jdkoeppen/waxstack
