language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: CIafvRKzl12Ez4KSDKevBDhuN6GqY7hCoQsG59hrgUVRhDIZFGpDtcoaE2pYJOnQahmIEIqdAFAPgQ4RQcUWyAUjG8lOBDDcgrpIjhP5EcYGExtwzYhrHvv5iwzygm3ZXNgb6DluC2AEUvTfu8BTRwFR0MgtOZnzjLZXPqv4vz5a/3gTPiBNw+Il0UHooYGdzPp8EwX7lGNgU0y1Qo/Z//sEIUJORej0pB+0WzLMEUVqNSDUiOfbw3s3sKlo++ieFrfTzzhAqsAYBUIUNhkYYMamzv41GXGzKEOn3ImUAHPAyz98oMkkK+MNt1hpIcPTbQJI3MKoZtbaohR0dRtTpsKkLWh+fGQICq/XP9+XlR2qZq1c5bRkIuq5g/S6f2I6/xyaDhUqcSkga674e/Koin/Pbrr0DARz76M3j3ruBg+Rt8EtTHPATKijHL0IPki4DmtUHRphNACovoROsh4IBp14WrVx98v2Q053r6+KEOWDOoMWNJeGQOxJWPuv4/gbGyxFOfNaEQmTA4jhoIaDTh85idjyTiDrSnkYekhBuaA56OuEOyd2mH4uImIJCFPdKEVvMFkXhDjQly0ysNSKbXORRYfmDB+u0d9NrHtoe3k2CHZWSjLZVBQOU6OCxfORyqTdLhb4x10kAP3xLuhoETIgitZq1qn7UnHLJxThM98=
  app: waxstack
  on:
    repo: jdkoeppen/waxstack
